### PR TITLE
Made Routes, Controllers, middlewares and resolved errors for opening chatbot and game in same window 

### PR DESCRIPTION
**Pull request by sharmavasant**
## Description
Made routes, controllers, middlewares and resolved some errors to open chatbot and game in same window when chatbot or game buttons are clicked without opening them in another window.

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Made controllers for rendering index pages of chatbot and 2 games. 
Made middlewares for authenticating and finally routes.
Adjusted the ports for hosting them in same window.
Added .env file for environment variables.
Changed react-scripts to react-scripts --openssl-legacy-provider in package.json of frontend.
After all this as per the issue if we click on chatbot button or any game button then it will open in same window.

## Related Issue

Fixes # ([issue](https://github.com/ContriHUB/PlayTopia/issues/3))

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Motivation and Context

If this issue not solved then it will lead to many windows for the same website.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

After adding controllers, middlewares and routes, when buttons were clicked they opened chatbot window or games window in same window as previous.
**Instructions:**
cd backend -> npm i -> npm start
cd frontend-> npm i -> npm start
cd Games -> cd 2048-animated -> npm i -> npm start
cd Games -> cd memory-game -> npm i -> npm start

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Review by silkie261001 — APPROVED** [review]

**Comment by sharmavasant** [comment]
@silkie261001 did my contribution solved the issue?

**Comment by silkie261001** [comment]
no, have u tried on you pc. If its working send me some screenshots.

**Comment by sharmavasant** [comment]
> no, have u tried on you pc. If its working send me some screenshots.
@silkie261001 
All contents opening in same window tab.
Screenshot (3)
Screenshot (4)
Screenshot (5)
Screenshot (6)

**Comment by silkie261001** [comment]
You are running all the games and chatbot in different ports. Try
connecting all the different ports by making routes and build the
connection

**Comment by sharmavasant** [comment]
means all chatbot and game should open in 3000 port?
@silkie261001

**Comment by silkie261001** [comment]
Yes

**Comment by sharmavasant** [comment]
I'm trying to connect all ports to 5000 port
```
const { createProxyMiddleware } = require("http-proxy-middleware");
//Proxy configuration for React App 1 (running on port 3456)
const reactApp1Proxy = createProxyMiddleware("/app1", {
  target: "http://127.0.0.1:3456", // React App 1's development server
  changeOrigin: true,
});
//http://localhost:3456/
// Proxy configuration for React App 2 (running on port 3457)
const reactApp2Proxy = createProxyMiddleware("/app2", {
  target: "http://127.0.0.1:3457", // React App 2's development server
  changeOrigin: true,
});

const reactApp3Proxy = createProxyMiddleware("/app3", {
  target: "http://127.0.0.1:3000", // React App 2's development server 
  changeOrigin: true,
});

// Use proxy middleware for both apps
app.use("/app1", reactApp1Proxy);
app.use("/app2", reactApp2Proxy);
app.use("/app3", reactApp3Proxy);
```
But this is giving error.
Screenshot (7)
@silkie261001

**Comment by mangalgithub** [comment]
Hey @silkie261001 can you elaborate about this issue and what you want as the result

**Comment by silkie261001** [comment]
Like in the current website all the pages are running on different local
ports, but now you have to run all of them inside a single port.

**Pull request merged**
