### PR TITLE
Themes updated

### PR DESCRIPTION
**Pull request by Ishsinghal**
## Description

- themes.js (context provider for setting background themes )

## Related Issue
 No functionality for switching to dark and light mode

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Screenshots (if appropriate):
[screen-capture (2).webm](https://github.com/ContriHUB/PlayTopia/assets/125989792/17738329-7ae6-4fd9-b972-ce2f35ccaab3)

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Ishsinghal** [comment]
Work is on the way , will complete it today itself..

**Comment by silkie261001** [comment]
make the button look more good

**Comment by Ishsinghal** [comment]
[screen-capture (3).webm](https://github.com/ContriHUB/PlayTopia/assets/125989792/61ef6396-0d7e-40a4-8c08-f23a5895bc94)

**Review by silkie261001 — DISMISSED** [review]

**Comment by silkie261001** [comment]
once recheck it. It is not running correctly on my system

**Comment by Ishsinghal** [comment]
But mam , it is correctly working on my system.
once recheck it....

**Review by silkie261001 — APPROVED** [review]

**Pull request merged**
