### PR TITLE
feat: share emoji's in video conferencing

### LINKED ISSUE #7: Option to react with emojis during livestream.
Implement a feature to give option to users to react with emojis during a live stream.

### PR DESCRIPTION
**Pull request by lokesh-wagh**
## Description
I have fixed some bug's that were preventing the deployment of the project's
I have fixed send friend invitation (no invite was being sent)

then i have added a component to pick emoji's

i have also enabled json data to be transferred over P2P connection (which i have used for sharing emoji's)

in the first few files i have just replaced process.env with my own secret string so that newcomer's don't get thrown with a lot of error's

then in backend/socketServer file i have made the server listening to the port that it was supposed to listen at

then in frontend/src/Dashboard/FriendsSideBar/AddFriendButton.js i have added a method that would actually send the invite to the backend

frontend/src/Dashboard/FriendsSideBar/AddFriendButton.js here i have added the actual emoji sidebar

frontend/src/Dashboard/Room/RoomButtons/emojiButton.js here the emoji tray has been added that can be used to send various emoji's

frontend/src/Dashboard/Room/RoomButtons/RoomButtons.js
here i have added the Emoji Picker to room button's so that it can be accesible

in frontend/src/Dashboard/Room/VideosContainer.js i have added a new styled div by the name of VideoWrapper
this div contain's both the div that is displaying the emoji and the video as well

frontend/src/realtimeCommunication/socketConnection.js i have stored the socket id in localstorage for access later

in frontend/src/realtimeCommunication/webRTCHandler.js i have added a exchange data event to all the peer's and three method's

handleExchangeData : facilitate's the exchange of data through peer's
AddEmoji : add's the emoji to it's right video container and also remove's it from there after 2s
getPeer's : return's the active peer's object  

## Related Issue

Fixes #7 
Closes #7 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by lokesh-wagh** [comment]
@silkie261001 
Mam the PR is not complete yet i just wanted you to suggest some styling 
like where should the shared emoji's appear

then i will apply those styling and complete the pr

**Comment by lokesh-wagh** [comment]
here's the progress so far

[webrtc.mp4.webm](https://github.com/ContriHUB/PlayTopia/assets/129964049/112961d6-42ab-4f64-9cb3-0c255445724d)

**Comment by silkie261001** [comment]
Like you can create one bar containing emojis in the video call container.

**Comment by lokesh-wagh** [comment]
i have a pop up for picking emoji's
should i add a bar below with some commonly used emoji's??

**Comment by silkie261001** [comment]
Yes, you can do that.

**Comment by lokesh-wagh** [comment]
and where should the sent emoji pop??

**Comment by silkie261001** [comment]
It can pop anywhere in the stream in mid or bottom, anywhere as per you
convenience.

**Comment by lokesh-wagh** [comment]
[screen-capture (5).webm](https://github.com/ContriHUB/PlayTopia/assets/129964049/debff34a-ce2f-4b82-84b7-8a353ab0fcfb)

added the bar

**Comment by lokesh-wagh** [comment]
@silkie261001 
the PR is ready for review now 

i have explained all the change's by updating the first comment of the PR thread

**Comment by lokesh-wagh** [comment]
@silkie261001 
i have sent link for the pr on sac website

**Review by silkie261001 — APPROVED** [review]

**Comment by lokesh-wagh** [comment]
Thank you for guidance mam!!

**Comment by silkie261001** [comment]
You have done a great job.

**Pull request merged**
