### PR TITLE
Display Chat between users

### PR DESCRIPTION
**Pull request by MrinalVarshney**
## Description

- Some bug fixes in backend for retrieving messages 
- Added profile Image field on necessary places , so that it can be shown while chat is going on
- During register and login no userId was being sent , which is giving error during display messages, So i have included 
  userId in the the response json from backend while login and signup activities.

## Related Issue

- No live chat is displayed earlier while users are online.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Screenshots (if appropriate):
[screen-capture (4).webm](https://github.com/ContriHUB/PlayTopia/assets/66404121/8cbad8c0-26ea-41cb-9d4b-fdb91a3c0b5b)

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by MrinalVarshney** [comment]
Moreover some styling and animations are left , will do it asap !

**Comment by MrinalVarshney** [comment]
UI interface modified ,
[screen-capture (5).webm](https://github.com/ContriHUB/PlayTopia/assets/66404121/221cf963-7f92-44b0-acdd-b56aa61f217e)

**Comment by silkie261001** [comment]
can you decrease that lag between pressing button and displaying of message

**Comment by MrinalVarshney** [comment]
Shall I display something like "loading messages..." till they are not fetched ?

**Comment by silkie261001** [comment]
Yes, you can do that.

**Comment by MrinalVarshney** [comment]
ok mam

**Comment by MrinalVarshney** [comment]
It's done !
[screen-capture (6).webm](https://github.com/ContriHUB/PlayTopia/assets/66404121/9745bbd4-21d4-46bc-aa9d-3254a794e999)

**Review by silkie261001 — APPROVED** [review]

**Pull request merged**
