### PR TITLE
Feat/Option to add customised profile photo.

### PR DESCRIPTION
**Pull request by MrinalVarshney**
## Description

**At Frontend**
1.  Creation of a  **useState** and **input box** for file upload
2.  Uploadation of image on **"Cloudinary"** (cloud storage)  
3.  Generation of the **access link** of **image** which is uploaded on **cloud** 
4.  Modification in css of "Box" component in AuthBox.js making it adjustable accroding to height of the content

**At Backend**
1. Addition of new field **"profileImage"** in **User Modal**
2. Modification of  **registerSchema** in **authRoutes.js** for accepting **profileImages**
3. **Profile image** url saved on **mongoose**
4. Modification in **register and login responses** , includes **transfer of image link to frontend** along with other user details

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**I have use cloudinary because**  it provides

-Seamless Image Management
- Performance Optimization
- Content Delivery
- Security
- User-Friendly APIs
- Cost Efficiency
- Scalability

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Screenshots (if appropriate):
[screen-capture (2).webm](https://github.com/ContriHUB/PlayTopia/assets/66404121/bfe778e6-4b8d-43dd-9d5c-fd0a43046be0)

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by silkie261001** [comment]
you also have to display this photo as a icon when we start a call using "+" button, not only talking the input

**Comment by MrinalVarshney** [comment]
Ok mam

**Comment by MrinalVarshney** [comment]
Shall I display it on blue bar which is having options or in the box where video is streamed

**Comment by silkie261001** [comment]
Yes you can place it on the button when call is ongoing. Or you can make
one seperate button of user after login for photo displayed there.

**Comment by MrinalVarshney** [comment]
ok mam, will complete it by today itself ..

**Comment by MrinalVarshney** [comment]
All changes done !
Added a custom user Profile icon which can be used for showing user Profile details ..
[screen-capture (3).webm](https://github.com/ContriHUB/PlayTopia/assets/66404121/1a27f490-9dfd-4fb5-aefe-9faa10480af3)

**Review by silkie261001 — APPROVED** [review]

**Review by silkie261001 — APPROVED** [review]

**Pull request merged**
